### ISSUE TITLE
allow an options object to be passed to the main function

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/ask-once#4]
might be less logic and easier to define if we just support passing an options object instead of a list of arguments. 

that way users can also define `store` and `questions` however they want, e.g. and not in an explicit order on the args

**Comment by jonschlinkert** [comment]
https://github.com/doowb/ask-once/commit/4f16b87d13b2cb281c5fb7b1ac98342eb37107eb

**Comment by doowb** [comment]
I'll get this published soon unless you want to do it.

**Comment by jonschlinkert** [comment]
no rush, I can wait. thx

**Comment by doowb** [comment]
published as 0.3.1. Thanks for keeping it backwards compatible.
