### ISSUE TITLE
ask all questions

### ISSUE THREAD

**Issue by tunnckoCore** [doowb/ask-once#9]
Would be good.

``` js
var questions = require('question-cache')()
var store = require('data-store')('.twitter-auth', {cwd: process.cwd()})

questions
.set('consumer_key', 'Give your consumer key')
.set('consumer_secret', 'Give your consumer secret')
.set('access_token', 'Give your consumer token')
.set('access_secret', 'Give your consumer access secret')

var ask = require('ask-once')({
  questions: questions,
  store: store
})

ask(function (err, answers) {
  console.log(answers)
  //=> answers object as seen in `questions.ask(callback)`
})
```

instead of callback pyramid of doom

``` js
ask(function (err, answer) {
  console.log(err, answer)
  ask('consumer_secret', function (err, answer) {
    console.log(err, answer)

    ask('access_token', function (err, answer) {
      console.log(err, answer)

      ask('access_secret', function (err, answer) {
        console.log(err, answer)
      })
    })
  })
})
```

I think will be easy to implement.

**Comment by tunnckoCore** [comment]
Can be something like this, very raw and very ugly, just playing.

``` js
    opts = utils.merge({data: {}}, config, opts);
    if (typeof key === 'function') {
      cb = key
      var res = {}
      var keys = Object.keys(opts.questions.cache)
      keys.forEach(function (key) {
        if (opts.store.data.hasOwnProperty(key)) {
          res[key] = opts.store.data[key]
        } else {
          opts.questions.ask(key, function (err, answer) {
            if (err) return cb(err);

            // save answer to store
            store.set(answer);
            res[key] = utils.get(answer, key)
          });
        }
      })
      cb(null, res)
      return
    }
```

**Comment by tunnckoCore** [comment]
Actually.. accidently i rewrite it. But without the defaulting store thing. 
Both `ask all` and `ask single` works.

Please try
**askme.js**

``` js
var nal = require('now-and-later')

function askme (opts) {
  var res = {}
  opts = opts || {}
  opts.data = opts.data || {}
  opts.init = opts.init || false
  opts.force = opts.force || false

  return function (key, cb) {
    if (typeof key === 'function') {
      cb = key
      key = false
    }
    if (typeof cb !== 'function') {
      throw new TypeError('expect a done callback function')
    }

    if (!key) {
      nal.mapSeries(Object.keys(opts.questions.get()), iterator, function (err) {
        cb(err, res)
      })
      return
    }

    function iterator (k, next) {
      var value = opts.store.get(k)
      if (opts.init === true) {
        opts.store.del({force: true})
      }
      if (value) {
        opts.questions.cache[k].default = value
      }
      if (opts.init || opts.force || !opts.store.has(k)) {
        opts.questions.ask(k, function (err, answer) {
          if (err) return next(err)
          res[k] = answer[k]
          opts.store.set(k, res[k])
          next(null, res[k])
        })
        return
      }
      res[k] = value
      next(null, res[k])
    }

    iterator(key, cb)
  }
}
```

**example.js**

``` js

var questions = require('question-cache')()
var store = require('data-store')('example', {cwd: process.cwd()})
var argv = require('minimist')(process.argv.slice(2), {
  alias: {force: 'f', init: 'i', a: 'ask'}
})

questions
  .set('foo', 'What you think for `foo`:')
  .set('bar', 'Give your `bar` here:')
  .set('baz', 'And what about baz:')
  .set('qux', 'Foo bar baz, now qux:')

var ask = require('./askme')({
  questions: questions,
  store: store,
  init: argv.init,
  force: argv.force
})

ask(argv.ask || false, function (err, answers) {
  console.log(err, answers)
})
```

### commands

ask all questions once and save them

```
node example.js
? What you think for `foo`: one
? Give your `bar` here: two
? And what about baz: three
? Foo bar baz, now qux: four
null { foo: 'one', bar: 'two', baz: 'three', qux: 'four' }
```

get all answers

```
node example.js
null { foo: 'one', bar: 'two', baz: 'three', qux: 'four' }
```

get specific question answer

```
node example.js --ask qux
null 'four'
```

ask all, but rewrite answers, also show/use previous value as default

```
node example --force
? What you think for `foo` (one): abc
? Give your `bar` here (two):
? And what about baz (three):
? Foo bar baz, now qux (four): efg
null { foo: 'abc', bar: 'two', baz: 'three', qux: 'efg' }
```

delete the store and ask single question

```
node example.js --init --ask baz
? Give your `bar` here: foobar
null { baz: 'foobar' }
```

get single question

```
node example.js --ask baz
null 'foobar'
```

ask single and rewrite the answer

```
node example.js --force --ask baz
? Give your `bar` here (foobar): hello
null { baz: 'hello' }
```

get the answer of given question

```
node example.js --force --ask baz
null { baz: 'hello' }
```

**Comment by doowb** [comment]
I had just started writing a response when your's popped up...

We had discussed this and I think it's better to keep it to asking one at a time and build other libraries around groups of questions like [ask-for-github-auth](https://github.com/doowb/ask-for-github-auth).

I was going to suggest that you can use something like `async` (you picked `now-and-later`) to iterate over an array of questions. I think this is better to do as a user because `question-cache` allows nested question groups and picking questions with deep keys... `foo.bar.baz`. I think this adds more complexity to `ask-once` that should be handled by an implementing library where the programmer has specific control over what's being asked. For example, in `ask-for-githhub-auth`, I'm asking different questions based on the answers to previous questions.

I think there can be another library that wraps this one that asks all questions, but I don't know if it belongs here. I think you can make the above code into a wrapper library, and I'll be happy to review :grinning: .

**Comment by tunnckoCore** [comment]
> allows nested question groups and picking questions with deep keys

hm.. actually, just forgot for this, :laughing:  but it almost works, need little bit tweak.

> For example, in ask-for-githhub-auth, I'm asking different questions based on the answers to previous questions.

Yea, understand. Another specific use case. Maybe this would be the difference between both libraries. Because my use case is that i just want to save them and edit them if need at some point in time and they not depends on each other.

But yea.. it's cool how i always tell to myself that "i just will open issue and let it", but always ends with some comments like this and with some solutions. LOL :laughing: 

I need it for Twitter Auth maybe will call it `ask-for-twitter-auth` on top of something like `ask-onetime`.

**Comment by doowb** [comment]
> always ends with some comments like this and with some solutions

That's what I like about open source. I'll keep this issue open until you (or someone) makes a wrapper lib.

**Comment by jonschlinkert** [comment]
:)

**Comment by tunnckoCore** [comment]
Huh, did it, nesting now works. It's awesome.
Okey I'll try to publish something soon.
But only I cant choose the name `question-store`, `ask-all`, `ask-and-save`. I think first is the best option cuz actually it is storing questions to the disk. Any thoughts on these or ideas for other?

**Comment by doowb** [comment]
I think `ask-all-once` would be good.

**Comment by jonschlinkert** [comment]
@tunnckoCore link back here if you create any of those libs.

**Comment by tunnckoCore** [comment]
Yea, okey, of course. :+1:
